version: 2.1

parameters:
  GHA_Actor:
    type: string
    default: ""
  GHA_Action:
    type: string
    default: ""
  GHA_Event:
    type: string
    default: ""
  GHA_Meta:
    type: string
    default: ""

# Anchors to prevent forgetting to update a version
os_version: &os_version ubuntu24
baselibs_version: &baselibs_version v7.32.0
bcs_version: &bcs_version v11.6.0
tag_build_arg_name: &tag_build_arg_name gcmversion

orbs:
  ci: geos-esm/circleci-tools@4

workflows:
  build-test:
    jobs:
      - ci/build:
          name: build-GEOSctm-on-<< matrix.compiler >>
          context:
            - docker-hub-creds
          matrix:
            parameters:
              compiler: [gfortran, ifort, ifx]
          baselibs_version: *baselibs_version
          repo: GEOSctm
          develop_repos: "GMAO_Shared GEOS_Util"
          persist_workspace: false # Needs to be true to run fv3/gcm experiment, costs extra
