version: 2.1

parameters:
  GHA_Actor:
    type: string
    default: ""
  GHA_Action:
    type: string
    default: ""
  GHA_Event:
    type: string
    default: ""
  GHA_Meta:
    type: string
    default: ""

# Anchors to prevent forgetting to update a version
os_version: &os_version ubuntu20
baselibs_version: &baselibs_version v7.25.0
bcs_version: &bcs_version v11.5.0
tag_build_arg_name: &tag_build_arg_name fv3version

orbs:
  ci: geos-esm/circleci-tools@2

workflows:
  build-test:
    jobs:

      # Build GEOSfvdycore
      - ci/build:
          name: build-GEOSfvdycore-as-<< matrix.fv_precision >>-on-<< matrix.compiler >>
          context:
            - docker-hub-creds
          matrix:
            parameters:
              compiler: [ifort, gfortran]
              fv_precision: ["R8"]
          baselibs_version: *baselibs_version
          repo: GEOSctm
          mepodevelop: false
          persist_workspace: false # Needs to be true to run fv3/gcm experiment, costs extra